package com.shapeide.rasadesa.databases.meal

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.shapeide.rasadesa.domains.Meal
import com.shapeide.rasadesa.networks.ResponseMeals
import com.shapeide.rasadesa.networks.models.MealModel

@Entity(tableName = "tbl_meals")
data class MealEntity constructor(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    @ColumnInfo(name = "id_meal") val idMeal: Int,
    @ColumnInfo(name = "meal") val strMeal: String?,
    @ColumnInfo(name = "drink_alternate") val strDrinkAlternate: String?,
    @ColumnInfo(name = "category") val strCategory: String?,
    @ColumnInfo(name = "area") val strArea: String?,
    @ColumnInfo(name = "instruction") val strInstructions: String?,
    @ColumnInfo(name = "meal_thumb") val strMealThumb: String?,
    @ColumnInfo(name = "tags") val strTags: String?,
    @ColumnInfo(name = "youtube") val strYoutube: String?,
    @ColumnInfo(name = "source") val strSource: String?,
    @ColumnInfo(name = "image_source") val strImageSource: String?,
    @ColumnInfo(name = "creative_common") val strCreativeCommonsConfirmed: String?,
    @ColumnInfo(name = "is_favorite") val is_favorite: Int? = 0,
    @ColumnInfo(name = "date_modified") val dateModified: String?,
    @ColumnInfo(name = "ingredient_1") val strIngredient1: String?,
    @ColumnInfo(name = "ingredient_2") val strIngredient2: String?,
    @ColumnInfo(name = "ingredient_3") val strIngredient3: String?,
    @ColumnInfo(name = "ingredient_4") val strIngredient4: String?,
    @ColumnInfo(name = "ingredient_5") val strIngredient5: String?,
    @ColumnInfo(name = "ingredient_6") val strIngredient6: String?,
    @ColumnInfo(name = "ingredient_7") val strIngredient7: String?,
    @ColumnInfo(name = "ingredient_8") val strIngredient8: String?,
    @ColumnInfo(name = "ingredient_9") val strIngredient9: String?,
    @ColumnInfo(name = "ingredient_10") val strIngredient10: String?,
    @ColumnInfo(name = "ingredient_11") val strIngredient11: String?,
    @ColumnInfo(name = "ingredient_12") val strIngredient12: String?,
    @ColumnInfo(name = "ingredient_13") val strIngredient13: String?,
    @ColumnInfo(name = "ingredient_14") val strIngredient14: String?,
    @ColumnInfo(name = "ingredient_15") val strIngredient15: String?,
    @ColumnInfo(name = "ingredient_16") val strIngredient16: String?,
    @ColumnInfo(name = "ingredient_17") val strIngredient17: String?,
    @ColumnInfo(name = "ingredient_18") val strIngredient18: String?,
    @ColumnInfo(name = "ingredient_19") val strIngredient19: String?,
    @ColumnInfo(name = "ingredient_20") val strIngredient20: String?,
    @ColumnInfo(name = "measure_1") val strMeasure1: String?,
    @ColumnInfo(name = "measure_2") val strMeasure2: String?,
    @ColumnInfo(name = "measure_3") val strMeasure3: String?,
    @ColumnInfo(name = "measure_4") val strMeasure4: String?,
    @ColumnInfo(name = "measure_5") val strMeasure5: String?,
    @ColumnInfo(name = "measure_6") val strMeasure6: String?,
    @ColumnInfo(name = "measure_7") val strMeasure7: String?,
    @ColumnInfo(name = "measure_8") val strMeasure8: String?,
    @ColumnInfo(name = "measure_9") val strMeasure9: String?,
    @ColumnInfo(name = "measure_10") val strMeasure10: String?,
    @ColumnInfo(name = "measure_11") val strMeasure11: String?,
    @ColumnInfo(name = "measure_12") val strMeasure12: String?,
    @ColumnInfo(name = "measure_13") val strMeasure13: String?,
    @ColumnInfo(name = "measure_14") val strMeasure14: String?,
    @ColumnInfo(name = "measure_15") val strMeasure15: String?,
    @ColumnInfo(name = "measure_16") val strMeasure16: String?,
    @ColumnInfo(name = "measure_17") val strMeasure17: String?,
    @ColumnInfo(name = "measure_18") val strMeasure18: String?,
    @ColumnInfo(name = "measure_19") val strMeasure19: String?,
    @ColumnInfo(name = "measure_20") val strMeasure20: String?,
) {
    fun asDomainModel(): Meal {
        return Meal(
            idMeal = idMeal,
            strMeal = strMeal,
            strDrinkAlternate = strDrinkAlternate,
            strCategory = strCategory,
            strArea = strArea,
            strInstructions = strInstructions,
            strMealThumb = strMealThumb,
            strTags = strTags,
            strYoutube = strYoutube,
            strSource = strSource,
            strImageSource = strImageSource,
            strCreativeCommonsConfirmed = strCreativeCommonsConfirmed,
            dateModified = dateModified,
            strIngredient1 = strIngredient1,
            strIngredient2 = strIngredient2,
            strIngredient3 = strIngredient3,
            strIngredient4 = strIngredient4,
            strIngredient5 = strIngredient5,
            strIngredient6 = strIngredient6,
            strIngredient7 = strIngredient7,
            strIngredient8 = strIngredient8,
            strIngredient9 = strIngredient9,
            strIngredient10 = strIngredient10,
            strIngredient11 = strIngredient11,
            strIngredient12 = strIngredient12,
            strIngredient13 = strIngredient13,
            strIngredient14 = strIngredient14,
            strIngredient15 = strIngredient15,
            strIngredient16 = strIngredient16,
            strIngredient17 = strIngredient17,
            strIngredient18 = strIngredient18,
            strIngredient19 = strIngredient19,
            strIngredient20 = strIngredient20,
            strMeasure1 = strMeasure1,
            strMeasure2 = strMeasure2,
            strMeasure3 = strMeasure3,
            strMeasure4 = strMeasure4,
            strMeasure5 = strMeasure5,
            strMeasure6 = strMeasure6,
            strMeasure7 = strMeasure7,
            strMeasure8 = strMeasure8,
            strMeasure9 = strMeasure9,
            strMeasure10 = strMeasure10,
            strMeasure11 = strMeasure11,
            strMeasure12 = strMeasure12,
            strMeasure13 = strMeasure13,
            strMeasure14 = strMeasure14,
            strMeasure15 = strMeasure15,
            strMeasure16 = strMeasure16,
            strMeasure17 = strMeasure17,
            strMeasure18 = strMeasure18,
            strMeasure19 = strMeasure19,
            strMeasure20 = strMeasure20,
        )
    }
}

fun ResponseMeals<MealModel>.asDomainModel(): Meal {
    val data: MealModel = meals[0]
    return Meal(
        idMeal = data.idMeal,
        strMeal = data.strMeal,
        strDrinkAlternate = data.strDrinkAlternate,
        strCategory = data.strCategory,
        strArea = data.strArea,
        strInstructions = data.strInstructions,
        strMealThumb = data.strMealThumb,
        strTags = data.strTags,
        strYoutube = data.strYoutube,
        strSource = data.strSource,
        strImageSource = data.strImageSource,
        strCreativeCommonsConfirmed = data.strCreativeCommonsConfirmed,
        dateModified = data.dateModified,
        strIngredient1 = data.strIngredient1,
        strIngredient2 = data.strIngredient2,
        strIngredient3 = data.strIngredient3,
        strIngredient4 = data.strIngredient4,
        strIngredient5 = data.strIngredient5,
        strIngredient6 = data.strIngredient6,
        strIngredient7 = data.strIngredient7,
        strIngredient8 = data.strIngredient8,
        strIngredient9 = data.strIngredient9,
        strIngredient10 = data.strIngredient10,
        strIngredient11 = data.strIngredient11,
        strIngredient12 = data.strIngredient12,
        strIngredient13 = data.strIngredient13,
        strIngredient14 = data.strIngredient14,
        strIngredient15 = data.strIngredient15,
        strIngredient16 = data.strIngredient16,
        strIngredient17 = data.strIngredient17,
        strIngredient18 = data.strIngredient18,
        strIngredient19 = data.strIngredient19,
        strIngredient20 = data.strIngredient20,
        strMeasure1 = data.strMeasure1,
        strMeasure2 = data.strMeasure2,
        strMeasure3 = data.strMeasure3,
        strMeasure4 = data.strMeasure4,
        strMeasure5 = data.strMeasure5,
        strMeasure6 = data.strMeasure6,
        strMeasure7 = data.strMeasure7,
        strMeasure8 = data.strMeasure8,
        strMeasure9 = data.strMeasure9,
        strMeasure10 = data.strMeasure10,
        strMeasure11 = data.strMeasure11,
        strMeasure12 = data.strMeasure12,
        strMeasure13 = data.strMeasure13,
        strMeasure14 = data.strMeasure14,
        strMeasure15 = data.strMeasure15,
        strMeasure16 = data.strMeasure16,
        strMeasure17 = data.strMeasure17,
        strMeasure18 = data.strMeasure18,
        strMeasure19 = data.strMeasure19,
        strMeasure20 = data.strMeasure20,
    )
}

fun ResponseMeals<MealModel>.asDatabaseModel(): MealEntity {
    val data: MealModel = meals[0]
    return MealEntity(
        idMeal = data.idMeal,
        strMeal = data.strMeal,
        strDrinkAlternate = data.strDrinkAlternate,
        strCategory = data.strCategory,
        strArea = data.strArea,
        strInstructions = data.strInstructions,
        strMealThumb = data.strMealThumb,
        strTags = data.strTags,
        strYoutube = data.strYoutube,
        strSource = data.strSource,
        strImageSource = data.strImageSource,
        strCreativeCommonsConfirmed = data.strCreativeCommonsConfirmed,
        dateModified = data.dateModified,
        strIngredient1 = data.strIngredient1,
        strIngredient2 = data.strIngredient2,
        strIngredient3 = data.strIngredient3,
        strIngredient4 = data.strIngredient4,
        strIngredient5 = data.strIngredient5,
        strIngredient6 = data.strIngredient6,
        strIngredient7 = data.strIngredient7,
        strIngredient8 = data.strIngredient8,
        strIngredient9 = data.strIngredient9,
        strIngredient10 = data.strIngredient10,
        strIngredient11 = data.strIngredient11,
        strIngredient12 = data.strIngredient12,
        strIngredient13 = data.strIngredient13,
        strIngredient14 = data.strIngredient14,
        strIngredient15 = data.strIngredient15,
        strIngredient16 = data.strIngredient16,
        strIngredient17 = data.strIngredient17,
        strIngredient18 = data.strIngredient18,
        strIngredient19 = data.strIngredient19,
        strIngredient20 = data.strIngredient20,
        strMeasure1 = data.strMeasure1,
        strMeasure2 = data.strMeasure2,
        strMeasure3 = data.strMeasure3,
        strMeasure4 = data.strMeasure4,
        strMeasure5 = data.strMeasure5,
        strMeasure6 = data.strMeasure6,
        strMeasure7 = data.strMeasure7,
        strMeasure8 = data.strMeasure8,
        strMeasure9 = data.strMeasure9,
        strMeasure10 = data.strMeasure10,
        strMeasure11 = data.strMeasure11,
        strMeasure12 = data.strMeasure12,
        strMeasure13 = data.strMeasure13,
        strMeasure14 = data.strMeasure14,
        strMeasure15 = data.strMeasure15,
        strMeasure16 = data.strMeasure16,
        strMeasure17 = data.strMeasure17,
        strMeasure18 = data.strMeasure18,
        strMeasure19 = data.strMeasure19,
        strMeasure20 = data.strMeasure20,
    )
}


fun List<MealEntity>.asDomainListModel(): List<Meal> {
    return map { id->
        Meal(
            idMeal = id.idMeal,
            strMeal = id.strMeal,
            strDrinkAlternate = id.strDrinkAlternate,
            strCategory = id.strCategory,
            strArea = id.strArea,
            strInstructions = id.strInstructions,
            strMealThumb = id.strMealThumb,
            strTags = id.strTags,
            strYoutube = id.strYoutube,
            strSource = id.strSource,
            strImageSource = id.strImageSource,
            strCreativeCommonsConfirmed = id.strCreativeCommonsConfirmed,
            dateModified = id.dateModified,
            strIngredient1 = id.strIngredient1,
            strIngredient2 = id.strIngredient2,
            strIngredient3 = id.strIngredient3,
            strIngredient4 = id.strIngredient4,
            strIngredient5 = id.strIngredient5,
            strIngredient6 = id.strIngredient6,
            strIngredient7 = id.strIngredient7,
            strIngredient8 = id.strIngredient8,
            strIngredient9 = id.strIngredient9,
            strIngredient10 = id.strIngredient10,
            strIngredient11 = id.strIngredient11,
            strIngredient12 = id.strIngredient12,
            strIngredient13 = id.strIngredient13,
            strIngredient14 = id.strIngredient14,
            strIngredient15 = id.strIngredient15,
            strIngredient16 = id.strIngredient16,
            strIngredient17 = id.strIngredient17,
            strIngredient18 = id.strIngredient18,
            strIngredient19 = id.strIngredient19,
            strIngredient20 = id.strIngredient20,
            strMeasure1 = id.strMeasure1,
            strMeasure2 = id.strMeasure2,
            strMeasure3 = id.strMeasure3,
            strMeasure4 = id.strMeasure4,
            strMeasure5 = id.strMeasure5,
            strMeasure6 = id.strMeasure6,
            strMeasure7 = id.strMeasure7,
            strMeasure8 = id.strMeasure8,
            strMeasure9 = id.strMeasure9,
            strMeasure10 = id.strMeasure10,
            strMeasure11 = id.strMeasure11,
            strMeasure12 = id.strMeasure12,
            strMeasure13 = id.strMeasure13,
            strMeasure14 = id.strMeasure14,
            strMeasure15 = id.strMeasure15,
            strMeasure16 = id.strMeasure16,
            strMeasure17 = id.strMeasure17,
            strMeasure18 = id.strMeasure18,
            strMeasure19 = id.strMeasure19,
            strMeasure20 = id.strMeasure20,
        )
    }
}